# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles/main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 800)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"border: none;\n"
"}\n"
"\n"
"#centralwidget{\n"
"background-color: white;\n"
"}\n"
"\n"
"/* NavBar Container */\n"
"#pomoFocusButton, #reportsButton, #rankingButton{\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"color: rgb(209, 209, 209)\n"
"}\n"
"\n"
"\n"
"#leftContainer{\n"
"border: 1px solid black;\n"
"background-color: rgb(44, 52, 60);\n"
"}\n"
"\n"
"\n"
"/* Body Container */\n"
"\n"
"/* PomoFocus Page */\n"
"\n"
"/* Pomo Container */\n"
"\n"
"#pomoFocusPage{\n"
"background-color: rgb(29, 35, 44);\n"
"}\n"
"\n"
"#pomoContainer{\n"
"border: 2px solid rgba(136, 136, 136, 100);\n"
"border-radius : 20px;\n"
"background-color:rgb(44, 52, 60)\n"
"}\n"
"\n"
"\n"
"#progressBar {\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"\n"
"#progressBar::chunk {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QSlider::groove:horizontal {\n"
"    border: 1px solid #d3d3d3;\n"
"    border-radius: 3px;\n"
"    height: 3px;\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #e1e1e1, stop:1 #f6f6f6);\n"
"    margin: 2px 0;\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: qradialgradient(cx:0.5, cy:0.5, fx:0.5, fy:0.5, radius: 0.5, stop:0 #ffffff, stop:1 #dcdcdc);\n"
"    border: 1px solid #d3d3d3;\n"
"    width: 40px;\n"
"    height:3px;\n"
"    margin: -7px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
"    border-radius: 8px;\n"
"}\n"
"\n"
"\n"
"#startStopButton {\n"
"background-color: #3498db; /* Cool blue background color */\n"
"border: 2px solid #2980b9; /* Darker blue border */\n"
"color: white; /* White text color */\n"
"padding: 8px 16px; /* Padding */\n"
"font-size: 40px; /* Font size */\n"
"border-radius: 10px; /* Rounded corners */\n"
"}\n"
"startStopButton:hover {\n"
"background-color: #2980b9; /* Darker blue background color on hover */\n"
"}\n"
"\n"
"#timerLabel{\n"
"font: 100pt \"MS Shell Dlg 2\";\n"
"color:white\n"
"}\n"
"\n"
"#subjectsComboBox{\n"
"border: 1px solid black;\n"
"background-color: rgb(29, 35, 44);\n"
"color: white;\n"
"padding: 3px\n"
"}\n"
"\n"
"#subjectsComboBox:disabled{\n"
"background-color: rgb(44, 52, 60);\n"
"border-color: lightgray\n"
"}\n"
"\n"
"/* Reports Page */\n"
"#reportsPage{\n"
"background-color: rgb(29, 35, 44);\n"
"}\n"
"\n"
"#barComboBox{\n"
"border: 1px solid grey;\n"
"border-radius: 4px;\n"
"background-color: rgb(29, 35, 44);\n"
"color: white;\n"
"padding: 3px\n"
"}\n"
"\n"
"#TabButton{\n"
"color:rgb(239, 89, 89);\n"
"font-weight: bold;\n"
"}\n"
"\n"
"#leftWeekButton{\n"
"color:rgb(239, 89, 89);\n"
"}\n"
"#rightWeekButton{\n"
"color:rgb(239, 89, 89);\n"
"}\n"
"\n"
"\n"
"#pomoStateLabel{\n"
"color:white;\n"
"font: 87 50pt \"Segoe UI Black\";\n"
"}\n"
"\n"
"/* Pie Chart Container */\n"
"\n"
"#pieChartWidget{\n"
"border: 2px solid rgba(136, 136, 136, 100);\n"
"}\n"
"\n"
"#noStudyLabel{\n"
"color: grey;\n"
"}\n"
"\n"
"/* Bar Chart Conratiner */\n"
"\n"
"#barsWidget{\n"
"border: 2px solid rgba(136, 136, 136, 100);\n"
"}\n"
"\n"
"#weekFrame{\n"
"\n"
"border-radius: 15px\n"
"}\n"
"\n"
"#weekLabel{\n"
"border-left: 2px solid orange;\n"
"border-right: 2px solid orange\n"
"}\n"
"\n"
"\n"
"/* Ranking Page */\n"
"#rankingPage{\n"
"background-color: rgb(29, 35, 44);\n"
"}\n"
"\n"
"#ranksWidget{\n"
"border: 2px solid rgba(136, 136, 136, 100);\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftContainer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.leftContainer.setStyleSheet("")
        self.leftContainer.setObjectName("leftContainer")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.leftContainer)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.leftContainer)
        self.widget.setObjectName("widget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.leftContainer)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.widget_2)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_5.setContentsMargins(50, -1, 0, -1)
        self.verticalLayout_5.setSpacing(20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.pomoFocusButton = QtWidgets.QPushButton(self.frame_2)
        self.pomoFocusButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pomoFocusButton.setStyleSheet("#pomoFocusButton{\n"
"background-color: rgb(29, 35, 44);\n"
"padding: 15px;\n"
"font-size: 20px;\n"
"border-top-left-radius: 30px\n"
"}\n"
"")
        self.pomoFocusButton.setObjectName("pomoFocusButton")
        self.verticalLayout_5.addWidget(self.pomoFocusButton)
        self.reportsButton = QtWidgets.QPushButton(self.frame_2)
        self.reportsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.reportsButton.setObjectName("reportsButton")
        self.verticalLayout_5.addWidget(self.reportsButton)
        self.rankingButton = QtWidgets.QPushButton(self.frame_2)
        self.rankingButton.setObjectName("rankingButton")
        self.verticalLayout_5.addWidget(self.rankingButton)
        self.verticalLayout_3.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.widget_2, 0, QtCore.Qt.AlignTop)
        self.label_4 = QtWidgets.QLabel(self.leftContainer)
        self.label_4.setStyleSheet("color: grey;\n"
"font: 6pt \"Terminal\";")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.leftContainer)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.frame_5 = QtWidgets.QFrame(self.leftContainer)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setItalic(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame = QtWidgets.QFrame(self.leftContainer)
        self.frame.setMinimumSize(QtCore.QSize(0, 10))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout.addWidget(self.frame)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 10)
        self.horizontalLayout.addWidget(self.leftContainer)
        self.rightContainer = QtWidgets.QWidget(self.centralwidget)
        self.rightContainer.setObjectName("rightContainer")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.rightContainer)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pagesStackedWidget = QtWidgets.QStackedWidget(self.rightContainer)
        self.pagesStackedWidget.setStyleSheet("")
        self.pagesStackedWidget.setObjectName("pagesStackedWidget")
        self.pomoFocusPage = QtWidgets.QWidget()
        self.pomoFocusPage.setObjectName("pomoFocusPage")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.pomoFocusPage)
        self.verticalLayout_9.setContentsMargins(20, 20, 20, 10)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.widget_7 = QtWidgets.QWidget(self.pomoFocusPage)
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.widget_3 = QtWidgets.QWidget(self.widget_7)
        self.widget_3.setMinimumSize(QtCore.QSize(0, 30))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.fullScreenButton = QtWidgets.QPushButton(self.widget_3)
        self.fullScreenButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fullScreenButton.setFont(font)
        self.fullScreenButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fullScreenButton.setStyleSheet("color: white")
        self.fullScreenButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/expand.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fullScreenButton.setIcon(icon)
        self.fullScreenButton.setObjectName("fullScreenButton")
        self.verticalLayout_4.addWidget(self.fullScreenButton)
        self.horizontalLayout_6.addWidget(self.widget_3, 0, QtCore.Qt.AlignLeft)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.visibilitySlider = QtWidgets.QSlider(self.widget_7)
        self.visibilitySlider.setFocusPolicy(QtCore.Qt.NoFocus)
        self.visibilitySlider.setMinimum(35)
        self.visibilitySlider.setProperty("value", 99)
        self.visibilitySlider.setOrientation(QtCore.Qt.Horizontal)
        self.visibilitySlider.setObjectName("visibilitySlider")
        self.horizontalLayout_6.addWidget(self.visibilitySlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_10.setContentsMargins(11, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.fixedWindowButton = QtWidgets.QPushButton(self.widget_6)
        self.fixedWindowButton.setEnabled(True)
        self.fixedWindowButton.setMinimumSize(QtCore.QSize(0, 30))
        self.fixedWindowButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fixedWindowButton.setFont(font)
        self.fixedWindowButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.fixedWindowButton.setStyleSheet("color: white")
        self.fixedWindowButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/forward.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.fixedWindowButton.setIcon(icon1)
        self.fixedWindowButton.setCheckable(False)
        self.fixedWindowButton.setObjectName("fixedWindowButton")
        self.verticalLayout_10.addWidget(self.fixedWindowButton)
        self.horizontalLayout_6.addWidget(self.widget_6, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_9.addWidget(self.widget_7, 0, QtCore.Qt.AlignTop)
        self.widget_4 = QtWidgets.QWidget(self.pomoFocusPage)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pomoContainer = QtWidgets.QWidget(self.widget_4)
        self.pomoContainer.setObjectName("pomoContainer")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.pomoContainer)
        self.verticalLayout_13.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.clockContainer = QtWidgets.QWidget(self.pomoContainer)
        self.clockContainer.setStyleSheet("")
        self.clockContainer.setObjectName("clockContainer")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.clockContainer)
        self.verticalLayout_7.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_3 = QtWidgets.QFrame(self.clockContainer)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pomoStateLabel = QtWidgets.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(50)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pomoStateLabel.setFont(font)
        self.pomoStateLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pomoStateLabel.setObjectName("pomoStateLabel")
        self.horizontalLayout_2.addWidget(self.pomoStateLabel)
        self.verticalLayout_7.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.clockContainer)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setStyleSheet("")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.timerLabel = QtWidgets.QLabel(self.frame_4)
        self.timerLabel.setStyleSheet("")
        self.timerLabel.setScaledContents(True)
        self.timerLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.timerLabel.setWordWrap(True)
        self.timerLabel.setObjectName("timerLabel")
        self.verticalLayout_8.addWidget(self.timerLabel)
        self.verticalLayout_7.addWidget(self.frame_4, 0, QtCore.Qt.AlignHCenter)
        self.progressBarWidget = QtWidgets.QFrame(self.clockContainer)
        self.progressBarWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.progressBarWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.progressBarWidget.setObjectName("progressBarWidget")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.progressBarWidget)
        self.verticalLayout_11.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.progressBar = QtWidgets.QProgressBar(self.progressBarWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_11.addWidget(self.progressBar)
        self.verticalLayout_7.addWidget(self.progressBarWidget)
        self.buttonsFrame = QtWidgets.QFrame(self.clockContainer)
        self.buttonsFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.buttonsFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.buttonsFrame.setObjectName("buttonsFrame")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.buttonsFrame)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pomoSettingsButton = QtWidgets.QPushButton(self.buttonsFrame)
        self.pomoSettingsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pomoSettingsButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/settings.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pomoSettingsButton.setIcon(icon2)
        self.pomoSettingsButton.setIconSize(QtCore.QSize(50, 50))
        self.pomoSettingsButton.setObjectName("pomoSettingsButton")
        self.horizontalLayout_7.addWidget(self.pomoSettingsButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.startStopButton = QtWidgets.QPushButton(self.buttonsFrame)
        self.startStopButton.setMinimumSize(QtCore.QSize(300, 0))
        self.startStopButton.setObjectName("startStopButton")
        self.horizontalLayout_7.addWidget(self.startStopButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.skipButton = QtWidgets.QPushButton(self.buttonsFrame)
        self.skipButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.skipButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/next.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.skipButton.setIcon(icon3)
        self.skipButton.setIconSize(QtCore.QSize(50, 50))
        self.skipButton.setObjectName("skipButton")
        self.horizontalLayout_7.addWidget(self.skipButton)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout_7.addWidget(self.buttonsFrame)
        self.verticalLayout_13.addWidget(self.clockContainer)
        self.bottomWidget = QtWidgets.QWidget(self.pomoContainer)
        self.bottomWidget.setObjectName("bottomWidget")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomWidget)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pomoSubjectLabel = QtWidgets.QLabel(self.bottomWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pomoSubjectLabel.setFont(font)
        self.pomoSubjectLabel.setStyleSheet("color: white")
        self.pomoSubjectLabel.setObjectName("pomoSubjectLabel")
        self.horizontalLayout_5.addWidget(self.pomoSubjectLabel)
        self.subjectsComboBox = QtWidgets.QComboBox(self.bottomWidget)
        self.subjectsComboBox.setMinimumSize(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.subjectsComboBox.setFont(font)
        self.subjectsComboBox.setFocusPolicy(QtCore.Qt.NoFocus)
        self.subjectsComboBox.setEditable(False)
        self.subjectsComboBox.setObjectName("subjectsComboBox")
        self.subjectsComboBox.addItem("")
        self.horizontalLayout_5.addWidget(self.subjectsComboBox)
        spacerItem6 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.addSubjectButton = QtWidgets.QPushButton(self.bottomWidget)
        self.addSubjectButton.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.addSubjectButton.setFont(font)
        self.addSubjectButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addSubjectButton.setStyleSheet("color: white")
        self.addSubjectButton.setObjectName("addSubjectButton")
        self.horizontalLayout_5.addWidget(self.addSubjectButton, 0, QtCore.Qt.AlignLeft)
        self.verticalLayout_13.addWidget(self.bottomWidget)
        self.verticalLayout_13.setStretch(0, 4)
        self.verticalLayout_13.setStretch(1, 1)
        self.horizontalLayout_3.addWidget(self.pomoContainer)
        self.horizontalLayout_3.setStretch(0, 3)
        self.verticalLayout_9.addWidget(self.widget_4)
        self.fireBaseDataFrame = QtWidgets.QWidget(self.pomoFocusPage)
        self.fireBaseDataFrame.setObjectName("fireBaseDataFrame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.fireBaseDataFrame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_6 = QtWidgets.QFrame(self.fireBaseDataFrame)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.userEmojiLabel = QtWidgets.QLabel(self.frame_6)
        self.userEmojiLabel.setObjectName("userEmojiLabel")
        self.horizontalLayout_14.addWidget(self.userEmojiLabel)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: white")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_14.addWidget(self.label_7)
        self.usersCountLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.usersCountLabel.setFont(font)
        self.usersCountLabel.setStyleSheet("color: white")
        self.usersCountLabel.setText("")
        self.usersCountLabel.setObjectName("usersCountLabel")
        self.horizontalLayout_14.addWidget(self.usersCountLabel)
        self.greenEmojiLabel = QtWidgets.QLabel(self.frame_6)
        self.greenEmojiLabel.setObjectName("greenEmojiLabel")
        self.horizontalLayout_14.addWidget(self.greenEmojiLabel)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: white")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_14.addWidget(self.label_8)
        self.usersOnlineLabel = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.usersOnlineLabel.setFont(font)
        self.usersOnlineLabel.setStyleSheet("color: white")
        self.usersOnlineLabel.setText("")
        self.usersOnlineLabel.setObjectName("usersOnlineLabel")
        self.horizontalLayout_14.addWidget(self.usersOnlineLabel)
        self.horizontalLayout_13.addWidget(self.frame_6)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem7)
        self.frame_7 = QtWidgets.QFrame(self.fireBaseDataFrame)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.instructionsButton = QtWidgets.QPushButton(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.instructionsButton.setFont(font)
        self.instructionsButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.instructionsButton.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instructionsButton.setIcon(icon4)
        self.instructionsButton.setObjectName("instructionsButton")
        self.verticalLayout_12.addWidget(self.instructionsButton)
        self.horizontalLayout_13.addWidget(self.frame_7)
        self.verticalLayout_9.addWidget(self.fireBaseDataFrame)
        self.verticalLayout_9.setStretch(1, 3)
        self.pagesStackedWidget.addWidget(self.pomoFocusPage)
        self.reportsPage = QtWidgets.QWidget()
        self.reportsPage.setObjectName("reportsPage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.reportsPage)
        self.verticalLayout_16.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_16.setSpacing(20)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.widget_5 = QtWidgets.QWidget(self.reportsPage)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(20)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.barsWidget = QtWidgets.QWidget(self.widget_5)
        self.barsWidget.setStyleSheet("background-color: rgb(44, 52, 60);\n"
"border-radius: 20px;\n"
"\n"
"")
        self.barsWidget.setObjectName("barsWidget")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.barsWidget)
        self.verticalLayout_15.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_8 = QtWidgets.QFrame(self.barsWidget)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setStyleSheet("")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.saveBarChartButton = QtWidgets.QPushButton(self.frame_10)
        self.saveBarChartButton.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveBarChartButton.setIcon(icon5)
        self.saveBarChartButton.setObjectName("saveBarChartButton")
        self.horizontalLayout_11.addWidget(self.saveBarChartButton)
        self.horizontalLayout_8.addWidget(self.frame_10, 0, QtCore.Qt.AlignLeft)
        self.weekFrame = QtWidgets.QFrame(self.frame_8)
        self.weekFrame.setMinimumSize(QtCore.QSize(300, 0))
        self.weekFrame.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.weekFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.weekFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.weekFrame.setObjectName("weekFrame")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.weekFrame)
        self.horizontalLayout_10.setContentsMargins(11, 0, 11, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.leftWeekButton = QtWidgets.QPushButton(self.weekFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.leftWeekButton.setFont(font)
        self.leftWeekButton.setStyleSheet("")
        self.leftWeekButton.setObjectName("leftWeekButton")
        self.horizontalLayout_10.addWidget(self.leftWeekButton)
        self.TabButton = QtWidgets.QPushButton(self.weekFrame)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.TabButton.setFont(font)
        self.TabButton.setStyleSheet("")
        self.TabButton.setObjectName("TabButton")
        self.horizontalLayout_10.addWidget(self.TabButton)
        self.rightWeekButton = QtWidgets.QPushButton(self.weekFrame)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.rightWeekButton.setFont(font)
        self.rightWeekButton.setStyleSheet("")
        self.rightWeekButton.setObjectName("rightWeekButton")
        self.horizontalLayout_10.addWidget(self.rightWeekButton)
        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(2, 1)
        self.horizontalLayout_8.addWidget(self.weekFrame, 0, QtCore.Qt.AlignHCenter)
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.barComboBox = QtWidgets.QComboBox(self.frame_11)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.barComboBox.setFont(font)
        self.barComboBox.setStyleSheet("color:white")
        self.barComboBox.setObjectName("barComboBox")
        self.barComboBox.addItem("")
        self.barComboBox.addItem("")
        self.horizontalLayout_12.addWidget(self.barComboBox)
        self.horizontalLayout_8.addWidget(self.frame_11, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_15.addWidget(self.frame_8)
        self.barChartWidget = QtWidgets.QWidget(self.barsWidget)
        self.barChartWidget.setObjectName("barChartWidget")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.barChartWidget)
        self.verticalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.verticalLayout_15.addWidget(self.barChartWidget)
        self.verticalLayout_15.setStretch(1, 5)
        self.horizontalLayout_9.addWidget(self.barsWidget)
        self.pieChartWidget = QtWidgets.QWidget(self.widget_5)
        self.pieChartWidget.setStyleSheet("background-color: rgb(44, 52, 60);\n"
"border-radius: 20px")
        self.pieChartWidget.setObjectName("pieChartWidget")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.pieChartWidget)
        self.verticalLayout_14.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.noStudyLabel = QtWidgets.QLabel(self.pieChartWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.noStudyLabel.setFont(font)
        self.noStudyLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.noStudyLabel.setObjectName("noStudyLabel")
        self.verticalLayout_14.addWidget(self.noStudyLabel)
        self.horizontalLayout_9.addWidget(self.pieChartWidget)
        self.horizontalLayout_9.setStretch(0, 5)
        self.horizontalLayout_9.setStretch(1, 3)
        self.verticalLayout_16.addWidget(self.widget_5)
        self.verticalLayout_16.setStretch(0, 5)
        self.pagesStackedWidget.addWidget(self.reportsPage)
        self.rankingPage = QtWidgets.QWidget()
        self.rankingPage.setObjectName("rankingPage")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.rankingPage)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.widget_8 = QtWidgets.QWidget(self.rankingPage)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_18.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.ranksWidget = QtWidgets.QWidget(self.widget_8)
        self.ranksWidget.setStyleSheet("background-color: rgb(44, 52, 60);\n"
"border-radius: 20px;\n"
"\n"
"")
        self.ranksWidget.setObjectName("ranksWidget")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.ranksWidget)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.tableWidget = QtWidgets.QTableWidget(self.ranksWidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setItem(0, 0, item)
        self.verticalLayout_19.addWidget(self.tableWidget)
        self.verticalLayout_18.addWidget(self.ranksWidget)
        self.horizontalLayout_15.addWidget(self.widget_8)
        self.pagesStackedWidget.addWidget(self.rankingPage)
        self.verticalLayout_6.addWidget(self.pagesStackedWidget)
        self.horizontalLayout.addWidget(self.rightContainer)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pagesStackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pomoFocusButton.setText(_translate("MainWindow", "PomoFocus"))
        self.reportsButton.setText(_translate("MainWindow", "Reports"))
        self.rankingButton.setText(_translate("MainWindow", "Ranking"))
        self.label_4.setText(_translate("MainWindow", "Join Our Network."))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.youtube.com/watch?v=Wh-0FcxP-kU\"><img src=\":/newPrefix/images/icons/youtube.png\" width=\"50\" height=\"50\"/></a></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://discord.com/channels/1188822654766022656/1188822655265148930\"><img src=\":/newPrefix/images/icons/discord.png\" width=\"50\" height=\"50\"/></a></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><a href=\"https://www.facebook.com/moadh.oueslati.5/\"><img src=\":/newPrefix/images/icons/facebook.png\" width=\"50\" height=\"50\"/></a></p></body></html>"))
        self.pomoStateLabel.setText(_translate("MainWindow", "Work"))
        self.timerLabel.setText(_translate("MainWindow", "00:00"))
        self.startStopButton.setText(_translate("MainWindow", "Start"))
        self.pomoSubjectLabel.setText(_translate("MainWindow", "Choose a subject to focus on : "))
        self.subjectsComboBox.setItemText(0, _translate("MainWindow", "No Subject"))
        self.addSubjectButton.setText(_translate("MainWindow", "+"))
        self.userEmojiLabel.setText(_translate("MainWindow", "👤"))
        self.label_7.setText(_translate("MainWindow", "Users :"))
        self.greenEmojiLabel.setText(_translate("MainWindow", "🟢"))
        self.label_8.setText(_translate("MainWindow", "Online :"))
        self.leftWeekButton.setText(_translate("MainWindow", "<"))
        self.TabButton.setText(_translate("MainWindow", "Week"))
        self.rightWeekButton.setText(_translate("MainWindow", ">"))
        self.barComboBox.setItemText(0, _translate("MainWindow", "Hour"))
        self.barComboBox.setItemText(1, _translate("MainWindow", "Percentage"))
        self.noStudyLabel.setText(_translate("MainWindow", "You haven\'t studied yet today."))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "#1"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "User"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "(HH:MM)"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("MainWindow", "Moadh"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
