# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles/usage_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Usage_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(650, 500)
        Dialog.setMinimumSize(QtCore.QSize(0, 0))
        Dialog.setMaximumSize(QtCore.QSize(650, 500))
        Dialog.setStyleSheet("*{\n"
"border: none;\n"
"}\n"
"\n"
"#Dialog{\n"
"    background-color: rgb(29, 35, 44)\n"
"}\n"
"\n"
"QPushButton {\n"
"    color: white;\n"
"    padding: 10px 20px;\n"
"    border-radius: 4px;\n"
"    font-size: 16px;\n"
"    width: 80px\n"
"}\n"
"\n"
"#okPushButton{\n"
"background-color: rgb(16, 48, 87);\n"
"color: grey\n"
"}\n"
"\n"
"#nextPushButton{\n"
"background-color: rgb(23, 77, 143);\n"
"}\n"
"\n"
"#paragraphLabel{\n"
"color: white;\n"
"font-size: 20px;\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.motherWidget = QtWidgets.QWidget(Dialog)
        self.motherWidget.setObjectName("motherWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.motherWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.imageWidget = QtWidgets.QWidget(self.motherWidget)
        self.imageWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.imageWidget.setStyleSheet("border: 3px solid red")
        self.imageWidget.setObjectName("imageWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.imageWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.imageLabel = QtWidgets.QLabel(self.imageWidget)
        self.imageLabel.setMaximumSize(QtCore.QSize(630, 350))
        self.imageLabel.setText("")
        self.imageLabel.setPixmap(QtGui.QPixmap(":/newPrefix/images/icons/first.png"))
        self.imageLabel.setScaledContents(True)
        self.imageLabel.setObjectName("imageLabel")
        self.verticalLayout_4.addWidget(self.imageLabel)
        self.verticalLayout_2.addWidget(self.imageWidget)
        self.widget = QtWidgets.QWidget(self.motherWidget)
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paragraphLabel = QtWidgets.QLabel(self.widget)
        self.paragraphLabel.setWordWrap(True)
        self.paragraphLabel.setObjectName("paragraphLabel")
        self.verticalLayout_3.addWidget(self.paragraphLabel)
        self.verticalLayout_2.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.motherWidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.okPushButton = QtWidgets.QPushButton(self.widget_3)
        self.okPushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.okPushButton.setObjectName("okPushButton")
        self.horizontalLayout.addWidget(self.okPushButton)
        self.nextPushButton = QtWidgets.QPushButton(self.widget_3)
        self.nextPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nextPushButton.setObjectName("nextPushButton")
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.verticalLayout_2.addWidget(self.widget_3, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.setStretch(0, 4)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.verticalLayout.addWidget(self.motherWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.paragraphLabel.setText(_translate("Dialog", "Click on the plus button to add a subject first."))
        self.okPushButton.setText(_translate("Dialog", "Ok"))
        self.nextPushButton.setText(_translate("Dialog", "Next"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Usage_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
