# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'styles/version_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Version_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 198)
        Dialog.setStyleSheet("#parentWidget{\n"
"background-color: rgb(208, 208, 208)\n"
"}\n"
"\n"
"#laterButton{\n"
"background-color: rgb(198, 198, 198);\n"
"color: rgb(255, 0, 0);\n"
"border: 1px solid red;\n"
"padding : 4px\n"
"}\n"
"")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parentWidget = QtWidgets.QWidget(Dialog)
        self.parentWidget.setObjectName("parentWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.parentWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget_3 = QtWidgets.QWidget(self.parentWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.updateMessage = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.updateMessage.setFont(font)
        self.updateMessage.setObjectName("updateMessage")
        self.verticalLayout_3.addWidget(self.updateMessage)
        self.label_4 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.parentWidget)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setFamily("Goudy Old Style")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setOpenExternalLinks(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout_2.addWidget(self.widget_2, 0, QtCore.Qt.AlignLeft)
        self.widget_4 = QtWidgets.QWidget(self.parentWidget)
        self.widget_4.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setContentsMargins(11, 0, -1, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.laterButton = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.laterButton.setFont(font)
        self.laterButton.setObjectName("laterButton")
        self.horizontalLayout_3.addWidget(self.laterButton)
        self.verticalLayout_2.addWidget(self.widget_4, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.parentWidget)

        self.retranslateUi(Dialog)
        self.laterButton.clicked.connect(Dialog.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.updateMessage.setText(_translate("Dialog", "<html><head/><body><p>🎉 <span style=\" font-weight:600;\">New Update Available! Atom Pomodoro 2.0</span> 🎉</p></body></html>"))
        self.label_4.setText(_translate("Dialog", "Tap to download the latest version and enjoy an enhanced Pomodoro experience!"))
        self.label_3.setText(_translate("Dialog", "> "))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><a href=\"https://mega.nz/folder/8O8yjbZJ#fKRvDcE7qsDm6_gnatGUJA\"><span style=\" text-decoration: underline; color:#0000ff;\">Download and Install</span></a></p></body></html>"))
        self.laterButton.setText(_translate("Dialog", "Later"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Version_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
